name: thelook_analytics

profile: thelook_analytics

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"


models:
  thelook_analytics:
    staging:
      +materialized: view
    marts:
      +materialized: table
